#!/bin/sh

set -e

echo "      _       _         __ _ _"
echo "   __| | ___ | |_      / _(_) | ___  ___"
echo "  / _\` |/ _ \| __|____| |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||_____|  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__|    |_| |_|_|\___||___/"
echo ""

cd ~

echo "==> Updating all the things..."

echo "  > Pulling master for all vim submodules..."
cd ~
git submodule foreach git pull origin master &> /dev/null


echo "==> Updating oh-my-zsh..."
echo "  > Rebasing against upstream..."
cd ~/.oh-my-zsh
git fetch upstream && git rebase upstream/master &> /dev/null
# git fetch upstream && git merge upstream/master &> /dev/null

echo "==> Done updating."
cd ~
git status -s -b
